name: Notify Discord on push to main

on:
  push:
    branches:
      - main

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Clona todo el historial de git

      - name: Get last commit info
        id: vars
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '"' | tr '\n' ' ')
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV

      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "Nuevo commit en la rama `main`: \n**Autor:** ${{ env.COMMIT_AUTHOR }} \n**Mensaje:** ${{ env.COMMIT_MESSAGE }} \n"
          }' \
          ${DISCORD_WEBHOOK}
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
