name: Notify Discord on push

on:
  push:
    branches:
      - '**'  # Esto captura cualquier rama en la que se haga un push

jobs:
  discordNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Clona todo el historial de git

      - name: Get last commit info
        id: vars
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          COMMIT_MESSAGE=$(git log -1 --pretty=%B | tr -d '"' | tr '\n' ' ')
          COMMIT_AUTHOR=$(git log -1 --pretty=%an)
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV

      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "¡Nuevo commit en la rama `${{ env.BRANCH_NAME }}`! \n**Autor:** ${{ env.COMMIT_AUTHOR }} \n**Commit:** ${{ env.COMMIT_MESSAGE }}\n**Detalles:** ${{ env.COMMIT_MESSAGE }}"
          }' \
          ${DISCORD_WEBHOOK}
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
